theme: jekyll-theme-slate
title: "Workshop on Computational Approaches to Subjectivity, Sentiment & Social Media Analysis"
description: "Subjectivity, Emotion and Sentiment Analysis"
url: https://wassa-workshop.github.io/
show_downloads: false
